version: '3.9'

services:
  DATABASE:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Viole07061999'
      MYSQL_DATABASE: quality_education
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - DATABASE_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: DATABASE  # Nama service db
      DB_USER: root
      DB_PASSWORD: 'Viole07061999'
      DB_NAME: quality_education
    depends_on:
      - DATABASE  # app bergantung pada db

volumes:
  DATABASE_data:
